
FROM alpine:3.19 AS base
RUN apk add --no-cache curl ca-certificates bash


WORKDIR /
RUN mkdir -p \
  /ComfyUI/models/text_encoders \
  /ComfyUI/models/vae \
  /ComfyUI/models/diffusion_models \
  /ComfyUI/models/loras

RUN wget -q https://huggingface.co/hijdese2020/facialsplash/resolve/main/wan22-f4c3spl4sh-100epoc-high-k3nk.safetensors -O /ComfyUI/models/loras/wan22-f4c3spl4sh-100epoc-high-k3nk.safetensors 
RUN wget -q https://huggingface.co/hijdese2020/facialsplash/resolve/main/wan22-f4c3spl4sh-154epoc-low-k3nk.safetensors  -O /ComfyUI/models/loras/wan22-f4c3spl4sh-154epoc-low-k3nk.safetensors  
RUN wget -q https://huggingface.co/hijdese2020/oral_insert/resolve/main/wan2.2-i2v-high-oral-insertion-v1.0.safetensors -O /ComfyUI/models/loras/wan2.2-i2v-high-oral-insertion-v1.0.safetensors 
RUN wget -q https://huggingface.co/hijdese2020/oral_insert/resolve/main/wan2.2-i2v-low-oral-insertion-v1.0.safetensors  -O /ComfyUI/models/loras/wan2.2-i2v-low-oral-insertion-v1.0.safetensors 
RUN wget -q https://huggingface.co/hijdese2020/breast_insert/resolve/main/wan2.2-i2v-high-breast-insertion-v1.0.safetensors  -O /ComfyUI/models/loras/wan2.2-i2v-high-breast-insertion-v1.0.safetensors 
RUN wget -q https://huggingface.co/hijdese2020/breast_insert/resolve/main/wan2.2-i2v-low-breast-insertion-v1.0.safetensors -O /ComfyUI/models/loras/wan2.2-i2v-low-breast-insertion-v1.0.safetensors 
RUN wget -q https://huggingface.co/hijdese2020/sex_fov/resolve/main/wan2.2-i2v-high-sex-fov-slider-v1.0.safetensors -O /ComfyUI/models/loras/wan2.2-i2v-high-sex-fov-slider-v1.0.safetensors  
RUN wget -q https://huggingface.co/hijdese2020/sex_fov/resolve/main/wan2.2-i2v-low-sex-fov-slider-v1.0.safetensors -O /ComfyUI/models/loras/wan2.2-i2v-low-sex-fov-slider-v1.0.safetensors 
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_tit/iGoon_Blink_Titjob_I2V_HIGH.safetensors -O /ComfyUI/models/loras/iGoon_Blink_Titjob_I2V_HIGH.safetensors  
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_tit/iGoon_Blink_Titjob_I2V_LOW.safetensors  -O /ComfyUI/models/loras/iGoon_Blink_Titjob_I2V_LOW.safetensors 
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_hand/iGoon_Blink_Handjob_I2V_HIGH.safetensors -O /ComfyUI/models/loras/iGoon_Blink_Handjob_I2V_HIGH.safetensors 
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_hand/iGoon_Blink_Handjob_I2V_LOW.safetensors  -O /ComfyUI/models/loras/iGoon_Blink_Handjob_I2V_LOW.safetensors  
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_blow/iGOON_Blink_Blowjob_I2V_HIGH.safetensors -O /ComfyUI/models/loras/iGOON_Blink_Blowjob_I2V_HIGH.safetensors 
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_blow/iGOON_Blink_Blowjob_I2V_LOW.safetensors  -O /ComfyUI/models/loras/iGOON_Blink_Blowjob_I2V_LOW.safetensors  
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_cum/iGoon_Blink_Facial_I2V_HIGH.safetensors -O /ComfyUI/models/loras/iGoon_Blink_Facial_I2V_HIGH.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_cum/iGoon_Blink_Facial_I2V_LOW.safetensors  -O /ComfyUI/models/loras/iGoon_Blink_Facial_I2V_LOW.safetensors 
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/allnsfw/wan22-k3nk4llinon3-15epoc-full-low-k3nk.safetensors -O /ComfyUI/models/loras/wan22-k3nk4llinon3-15epoc-full-low-k3nk.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/allnsfw/wan22-k3nk4llinon3-16epoc-full-high-k3nk.safetensors -O /ComfyUI/models/loras/wan22-k3nk4llinon3-16epoc-full-high-k3nk.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_ride/Blink_Squatting_Cowgirl_Position_I2V_HIGH.safetensors -O /ComfyUI/models/loras/Blink_Squatting_Cowgirl_Position_I2V_HIGH.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_ride/Blink_Squatting_Cowgirl_Position_I2V_LOW.safetensors  -O /ComfyUI/models/loras/Blink_Squatting_Cowgirl_Position_I2V_LOW.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_doggy/iGoon-Blink_Front_Doggystyle_I2V_HIGH.safetensors    -O /ComfyUI/models/loras/iGoon-Blink_Front_Doggystyle_I2V_HIGH.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/blink_doggy/iGoon-Blink_Front_Doggystyle_I2V_LOW.safetensors     -O /ComfyUI/models/loras/iGoon-Blink_Front_Doggystyle_I2V_LOW.safetensors 


# Imagen final de assets con solo /ComfyUI/models
FROM scratch
COPY --from=base /ComfyUI/models/loras /ComfyUI/models/loras
