
# syntax=docker/dockerfile:1.7
#FROM wlsdml1114/multitalk-base:1.8 AS base


FROM alpine:3.19 AS base
RUN apk add --no-cache curl ca-certificates bash


WORKDIR /
RUN mkdir -p \
  /ComfyUI/models/text_encoders \
  /ComfyUI/models/vae \
  /ComfyUI/models/diffusion_models \
  /ComfyUI/models/loras

# HuggingFace (público)
RUN wget -q https://huggingface.co/BigDannyPt/Wan-2.2-Remix-GGUF/resolve/main/I2V/v3.0/Low/wan22RemixT2VI2V_i2vLowV30-Q8_0.gguf -O /ComfyUI/models/diffusion_models/wan22RemixT2VI2V_i2vLowV30-Q8_0.gguf 

# Imagen final de assets con solo /ComfyUI/models
FROM scratch
COPY --from=base /ComfyUI/models /ComfyUI/models
