
FROM alpine:3.19 AS base
RUN apk add --no-cache curl ca-certificates bash


WORKDIR /
RUN mkdir -p \
  /ComfyUI/models/text_encoders \
  /ComfyUI/models/vae \
  /ComfyUI/models/diffusion_models \
  /ComfyUI/models/loras
                      
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/double_pen/Pornmaster_wan2.2_14b_I2V_double_penetration_v1_high_noise.safetensors -O /ComfyUI/models/loras/Pornmaster_wan2.2_14b_I2V_double_penetration_v1_high_noise.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/double_pen/Pornmaster_wan2.2_14b_I2V_double_penetration_v1_low_noise.safetensors -O /ComfyUI/models/loras/Pornmaster_wan2.2_14b_I2V_double_penetration_v1_low_noise.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/fullnelson/wan22-fullnelson-i2v-108epoc-high-k3nk.safetensors -O /ComfyUI/models/loras/wan22-fullnelson-i2v-108epoc-high-k3nk.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/fullnelson/wan22-fullnelson-i2v-368epoc-low-k3nk.safetensors -O /ComfyUI/models/loras/wan22-fullnelson-i2v-368epoc-low-k3nk.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/oral_fem/wan22-cunilingus-I2V-106epoc-high.safetensors -O /ComfyUI/models/loras/wan22-cunilingus-I2V-106epoc-high.safetensors
RUN wget -q https://huggingface.co/datasets/hijdese2020/wan22_datalora/resolve/main/oral_fem/wan22-cunilingus-I2V-72epoc-low.safetensors -O /ComfyUI/models/loras/wan22-cunilingus-I2V-72epoc-low.safetensors
RUN wget -q https://huggingface.co/hijdese2020/cheekfk/resolve/main/FF-v3-high-120.safetensors -O /ComfyUI/models/loras/FF-v3-high-120.safetensors
RUN wget -q https://huggingface.co/hijdese2020/cheekfk/resolve/main/FF-v3-low-120.safetensors -O /ComfyUI/models/loras/FF-v3-low-120.safetensors


# Imagen final de assets con solo /ComfyUI/models
FROM scratch
COPY --from=base /ComfyUI/models/loras /ComfyUI/models/loras
